# ---------- Build ----------


FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY tsconfig.json ./
COPY src ./src

RUN npm run build


# ---------- Production ----------

FROM node:22-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=PROD

COPY package*.json ./

RUN npm ci --omit=dev && npm cache clean --force

COPY --from=build /app/dist ./dist

COPY knexfile.cjs ./
COPY migrations ./migrations
COPY seeds ./seeds

EXPOSE 3001

CMD ["node", "dist/server.js"]